version: 2.1
orbs:
    codecov: codecov/codecov@1.1.3
    gh: circleci/github-cli@1.0.3
    browser-tools: circleci/browser-tools@1.2.4
jobs:
    build_library:
        docker:
            - image: cimg/node:14.19.0-browsers
        steps:
            - checkout
            - browser-tools/install-browser-tools
            - restore_cache:
                  keys:
                      - v2-dependencies-angular-{{ checksum "yarn.lock" }}
            - run:
                  name: Install Dependencies
                  command: |
                      yarn install --frozen-lockfile
            - save_cache:
                  name: Save Cache
                  paths:
                      - node_modules
                  key: v2-dependencies-angular-{{ checksum "yarn.lock" }}
            - run:
                  name: Prettier Check
                  command: |
                      yarn prettier:check
            - run:
                  name: Lint
                  command: |
                      yarn lint
            - run:
                  name: Test
                  command: |
                      yarn test:ci
            - run:
                  name: Build Library
                  command: |
                      yarn build:lib
            - run:
                  name: Test Artifacts
                  command: |
                      yarn test:artifacts
            - run:
                name: NPM Package
                command: |
                      cd dist && npm pack
            # Save the dist folder for use in future jobs.
            - persist_to_workspace:
                  root: .
                  paths:
                      - dist
                      - coverage
    coverage_report:
        working_directory: ~/angular-component-library
        docker:
            - image: cimg/node:14.19.0-browsers
        steps:
            - checkout
            - attach_workspace:
                at: .
            - codecov/upload:
                file: './coverage/lcov.info'
                token: dc22e69d-e76e-4c9c-92a4-92432b1033d4

    # Builds the Showcase app using @brightlayer-ui/angular-components persisted in /dist folder.
    build_showcase:
        docker:
            - image: cimg/node:14.19.0-browsers
        environment:
            - MASTER_BRANCH: master
        steps:
            - checkout
            - attach_workspace:
                  at: .
            - run:
                  name: Initialize Submodule
                  command: |
                      git submodule init && git submodule update
            - restore_cache:
                  keys:
                      - v2-dependencies-angular-{{ checksum "showcase/yarn.lock" }}
            - run:
                  name: Install Dependencies
                  command: |
                      cd showcase
                      yarn install --frozen-lockfile

                      # Install the packed version of @brightlayer-ui/angular-components
                      PACKAGED_VERSION=`node -p "require('../../dist/package.json').version"`
                      yarn add ../../dist/brightlayer-ui-angular-components-$PACKAGED_VERSION.tgz
            - save_cache:
                  name: Save Cache
                  paths:
                      - showcase/node_modules
                  key: v2-dependencies-angular-{{ checksum "showcase/yarn.lock" }}
            - attach_workspace:
                  at: .
            - run:
                  name: Build Showcase
                  command: |
                      cd showcase
                      yarn build

    publish:
      docker:
        - image: cimg/node:14.19.0-browsers
      steps:
        - checkout
        - attach_workspace:
            at: .
        - run:
            name: Authenticate with registry
            command: |
              echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
              echo "//registry.yarnpkg.com/:_authToken=$NPM_TOKEN" >> ~/.npmrc
        - run:
            name: Publish @brightlayer-ui/angular-components
            command:  |
              yarn publish:package -b $CIRCLE_BRANCH
    tag:
      docker:
        - image: cimg/node:14.19.0-browsers
      steps:
        - checkout
        - gh/setup
        - run:
            name: Tag @brightlayer-ui/angular-components
            command: |
              yarn tag:package -b $CIRCLE_BRANCH

workflows:
    version: 2
    angular_library:
        jobs:
            - build_library
            - build_showcase:
                requires:
                    - build_library
            - publish:
                requires:
                    - build_showcase
                filters:
                    branches:
                        only:
                            - master
                            - dev
            - tag:
                requires:
                    - publish
                filters:
                    branches:
                        only:
                            - master
            - coverage_report:
                requires:
                    - build_library
                filters:
                    branches:
                        only:
                            - master
